#!/usr/bin/python3

import re
import subprocess
import sys
from getopt import getopt
import fileinput
from collections import Counter

from lxml import etree	#	ferramenta


def main():
    opts, resto = getopt(sys.argv[1:], "albdc")
    dop = dict(opts)
    
    # texto = ""

    # # Reads file
    # for line in fileinput.input(resto):
    #     texto += line

    tree = etree.parse("data/Posts.xml")	#	retorna um ElementTree object	 e não um Element object
    #print(etree.tostring(root, method='text', encoding="UTF-8"))	#	isto vai buscar apenas o texto
    #print(etree.tostring(root, encoding="UTF-8"))

    for elem in tree.iter():
    	print(elem.get("Id"))

    # root = tree.getroot()
    # print(root)
main()