#!/usr/bin/python3

import re
import subprocess
import sys
from getopt import getopt
import fileinput
from collections import Counter

from lxml import etree	#	ferramenta
import csv


#	faz o parse e retorna o objeto do tipo Element
def parseXML(filename):
	tree = etree.parse(filename)	#	retorna um ElementTree object e não um Element object

	root = tree.getroot()

	return root

def topN(filename, N, field, objective):
	root = parseXML(filename)

	d = {}

	for elem in root.iter():
		if elem.tag not in objective:
			d[elem.get("Id")] = int(elem.get(field))

	for elem in sorted(d.items(), key=lambda p: p[1], reverse=True):
		print(f"{elem[0]} | {elem[1]}")

	return d

def convertToExcel(dict, outputFile):
	file = outputFile + ".csv"
	print(file)
	w = csv.writer(open(file, "w"))
	
	for key, val in dict.items():
		w.writerow([key,val])

def writeDictionary(dict):
	root = etree.Element("comments")

	for key, val in dict.items(): 
		root.append(etree.Element("comment"))
		root.set("key", key)
		root.set("value", val)

	return root


def main():
    opts, resto = getopt(sys.argv[1:], "albdc")
    dop = dict(opts)
    
    # texto = ""

    # # Reads file
    # for line in fileinput.input(resto):
    #     texto += line

    d1 = topN("data/Comments.xml", 10, "Score", "comments")
    #convertToExcel(d1, "comments")
    #e = writeDictionary(d1)
    d2 = topN("data/Posts.xml", 10, "Score", "posts")
    d3 = topN("data/Users.xml", 10, "Reputation", "users")
    d4 = topN("data/Tags.xml", 10, "Count", "tags")

main()



